# --- Required options --- #

# Name of website
title: ttsalpha

# Your name to show in the footer
author: Son Tran

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Author's home: "https://ttsalpha.github.io"
  
# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/res/ttsalpha.png"

round-avatar: false

# --- Footer social media links --- #

share-links-active:
  twitter: true
  facebook: true
  linkedin: true


# Output options (more information on Jekyll's site)

markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
